# Generated by Django 4.2 on 2026-04-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_moto', models.CharField(choices=[('naked', 'Naked/Street'), ('automatica', 'Automática'), ('deportiva', 'Deportiva'), ('adventure', 'Adventure'), ('motocross', 'Motocross/Enduro'), ('cuatrimoto', 'Cuatrimoto')], max_length=100)),
                ('anio', models.IntegerField()),
                ('cilindraje', models.IntegerField()),
                ('tipo_combustible', models.CharField(default='Gasolina', max_length=50)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida')], default='disponible', max_length=20)),
                ('potencia_maxima', models.CharField(blank=True, max_length=100)),
                ('torque_maximo', models.CharField(blank=True, max_length=100)),
                ('peso', models.CharField(blank=True, max_length=50)),
                ('tipo_motor', models.CharField(blank=True, max_length=100)),
                ('velocidades', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'MOTOCICLETAS',
            },
        ),
    ]
