# Generated by Django 6.0.4 on 2026-04-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_moto', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('cilindraje', models.IntegerField()),
                ('tipo_combustible', models.CharField(max_length=50)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
