# Generated by Django 6.0.4 on 2026-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocicleta',
            name='tipo_moto',
            field=models.CharField(choices=[('naked', 'Naked/Street'), ('automatica', 'Automatica'), ('deportiva', 'Deportiva'), ('adventure', 'Adventure'), ('motocross', 'Motocross/Enduro'), ('cuatrimoto', 'cuatrimoto')], max_length=100),
        ),
        migrations.AlterModelTable(
            name='motocicleta',
            table='MOTOCICLETAS',
        ),
    ]
